nome =input ("Digite seu Nome:  ")
ano = int(input("Digite o ano "))
anona = int(input ("Digite o ano nascimento"))
idade = int (ano-anona)
print ("ola mundo aqui esta seus dados")
print ("Nome", nome)
print ("Idade", idade)